### ISSUE TITLE
destory 拼写错误

### ISSUE THREAD

**Issue by think2011** [HaoChuan9421/seamless-scroll#1]

**Comment by haochuan9421** [comment]
谢谢，你很细心

**Comment by haochuan9421** [comment]
![image](https://user-images.githubusercontent.com/5093611/54974357-bf215200-4fce-11e9-8110-b0dc22ec0f7b.png)
![image](https://user-images.githubusercontent.com/5093611/54974380-d2ccb880-4fce-11e9-9446-c32d9bce1bd9.png)

**Comment by haochuan9421** [comment]
已修改，再次感谢大佬指正
